### ISSUE TITLE
Better highlight of inline code

### ISSUE THREAD

**Issue by noraj1337** [lsegal/yard#1141]
As said in #1137 inline code block are not readable.

## Steps to reproduce

Generate inline code in a source file.

## Actual Output

As you can see for inline code, only the font size and style change a few, this is just the default from browser computation.

![](https://i.imgur.com/pUDmHqb.png)

## Expected Output

Inline code highlighted in a similar manner than code blocks.

![](https://i.imgur.com/mqZYhdc.png)

## The CSS

```css
p > code {
  padding: 1px 3px 1px 3px;
  border: 1px solid #E1E1E8;
  background: #F7F7F9;
  border-radius: 4px;
}
```

+ `p > code` selector in order not to affect code blocks but only inline code (normally inline code is always direct child of a `p` or sometimes a `div`).
+ `padding: 1px 3px 1px 3px` less huge than code blocks
+ `border: 1px solid #E1E1E8;` same border as code blocks
+ `background: #F7F7F9;` and `border-radius: 4px;` same background as code blocks

**Comment by noraj1337** [comment]
See PR #1142

**Comment by lsegal** [comment]
Fixed by #1142.

**Comment by noraj1337** [comment]
`p > code` was to avoid matching `pre > code` but is insufficient for example in list `li > code` is not matched and there are ton of other cases. In fact we want `*:not(pre) > code`.

I don't think that

```css
.docstring p > code, .docstring p > tt, .tags p > code, .tags p > tt {
  color: #c7254e; background: #f9f2f4; padding: 2px 4px; font-size: 1em;
  border-radius: 4px;
}
```

need to be changed.
