### ISSUE TITLE
Fails tests with ruby2.5 in debian & ubuntu

### ISSUE THREAD

**Issue by xnox** [lsegal/yard#1161]
## Steps to reproduce

Try to build debian/ubuntu package, or run tests, with ruby2.5

## Actual Output

```
Failures:

  1) YARD::CLI::YRI#initialize loads search paths
     Failure/Error: @yri = YARD::CLI::YRI.new

       #<File (class)> received :file? with unexpected arguments
         expected: (/\/\.yard\/yri_cache$/)
              got: ("gem.deps.rb")
       Diff:
       @@ -1,2 +1,2 @@
       -[/\/\.yard\/yri_cache$/]
       +["gem.deps.rb"]
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/gem_index.rb:11:in `find_all_by_name'
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/registry.rb:54:in `yardoc_file_for_gem'
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/cli/yri.rb:165:in `block in add_gem_paths'
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/gem_index.rb:19:in `each'
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/cli/yri.rb:164:in `add_gem_paths'
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/cli/yri.rb:36:in `initialize'
     # ./spec/cli/yri_spec.rb:52:in `new'
     # ./spec/cli/yri_spec.rb:52:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:127:in `block (2 levels) in <top (required)>'

  2) YARD::CLI::YRI#initialize uses DEFAULT_SEARCH_PATHS prior to other paths
     Failure/Error: @yri = YARD::CLI::YRI.new

       #<File (class)> received :file? with unexpected arguments
         expected: (/\/\.yard\/yri_cache$/)
              got: ("gem.deps.rb")
       Diff:
       @@ -1,2 +1,2 @@
       -[/\/\.yard\/yri_cache$/]
       +["gem.deps.rb"]
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/gem_index.rb:11:in `find_all_by_name'
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/registry.rb:54:in `yardoc_file_for_gem'
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/cli/yri.rb:165:in `block in add_gem_paths'
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/gem_index.rb:19:in `each'
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/cli/yri.rb:164:in `add_gem_paths'
     # /usr/share/rubygems-integration/all/gems/yard-0.9.12/lib/yard/cli/yri.rb:36:in `initialize'
     # ./spec/cli/yri_spec.rb:64:in `new'
     # ./spec/cli/yri_spec.rb:64:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:127:in `block (2 levels) in <top (required)>'
```

## Expected Output

All tests pass

## Environment details:

* OS: Ubuntu Bionic, to become 18.04 LTS
* Ruby version (`ruby -v`): 2.5.0
* YARD version (`yard -v`): 0.9.12
* Relevant software dependency/versions:
  * [log][log]
  * [artifacts][artifacts]
I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md
[log]: https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic/bionic/amd64/y/yard/20180302_075932_53819@/log.gz
[artifacts]: https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic/bionic/amd64/y/yard/20180302_075932_53819@/artifacts.tar.gz
