### ISSUE TITLE
Code listing titles could be styled in HTML output

### ISSUE THREAD

**Issue by skalee** [lsegal/yard#1240]
AsciiDoc [allows code listings to have titles](https://asciidoctor.org/docs/user-manual/#listing-blocks) (typically file name). However, they look ugly and confusing in YARD documentation. In particular, they are difficult to distinguish from regular paragraphs.

Obviously, using a custom template may help a lot. However, this issue should be addressed in a default template IMO.

I am not sure if this issue belongs to this repository or rather to https://github.com/docmeta/rubydoc.info.

## Steps to reproduce

Following AsciiDoc document was used to illustrate the issue:

```adoc
== In AsciiDoc...

This is a lead paragraph.  Code listing starts right below.

.test.rb
----
two = 1 + 1
eleven = "1" + "1"
raise if Failure.problem
----

This is the second paragraph.  Code listing has just ended.
```

With default settings, YARD translates it to a following piece of HTML:

```html
<div class="sect1">
<h2 id="_in_asciidoc">In AsciiDoc&#8230;&#8203;</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="title">test.rb</div>
<div class="content">
<pre>two = 1 + 1
eleven = "1" + "1"
raise if Failure.problem</pre>
</div>
</div>
<div class="listingblock">
<div class="title">test2.rb</div>
<div class="content">
<pre class="highlight"><code class="language-ruby" data-lang="ruby">two = 2 + 2
eleven = "2" + "2"
raise if Failure.problem</code></pre>
</div>
</div>
</div>
</div>
```

## Actual Output

<table><tr><td>

![issue3-actual](https://user-images.githubusercontent.com/154287/56109677-e0cc8400-5f51-11e9-877d-5a8652e411aa.png)

</table></tr></td>

## Expected Output

Something of similar quality like:

<table><tr><td>

![issue3-expected](https://user-images.githubusercontent.com/154287/56109680-e2964780-5f51-11e9-896a-ecd2f58c54f0.png)

</table></tr></td>

----

I can prepare CSS updates if this is non-controversial.

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by skalee** [comment]
@lsegal How about this one? Can I implement such feature, or is it something what doesn't fit to YARD for some reason?

**Comment by skalee** [comment]
cc @lsegal

**Comment by skalee** [comment]
@lsegal Two more ideas:

<table><tr><td>

![Zrzut ekranu 2019-12-12 o 03 09 07](https://user-images.githubusercontent.com/154287/70676629-19616080-1c8d-11ea-9072-482a382ac02e.png)

</td></tr></table>

<table><tr><td>

![Zrzut ekranu 2019-12-12 o 03 10 25](https://user-images.githubusercontent.com/154287/70676630-19616080-1c8d-11ea-92c4-fbdc0d525ea4.png)

</td></tr></table>

Achieved with a following CSS change (the darker variant is commented out):

```css
/* code block titles (supported in AsciiDoc) */
#filecontents .listingblock .title {
  padding: 9px 14px 9px 14px;
  margin-top: 4px;
  border: 1px solid #e1e1e8;
  background: #efeff1;
  /*background: #e1e1e8;*/
  border-radius: 4px;
  font-size: 1em;
  overflow-x: auto;
  line-height: 1.2em;
  margin-bottom: -9px;
}
```
