### ISSUE TITLE
Extra YAML file incorrectly converted to HTML

### ISSUE THREAD

**Issue by davispuh** [lsegal/yard#1299]
I've `.yaml` file which I added as extra file, but rendered HTML is unreadable because it's not correctly rendered to HTML, for example newlines aren't converted to `<br />`

## Steps to reproduce

1. Create some `.yaml` file
2. Add it as extra
3. Generate documentation

## Actual Output

![attels](https://user-images.githubusercontent.com/651800/71648739-e13fc180-2d10-11ea-8de4-93bd7b1da380.png)

html is
```html
      <div id="content"><div id='filecontents'><hr>

<p>sudo: false
language: ruby
cache: bundler
rvm:</p>

<ul>
<li>2.6.5
before_install: gem install bundler -v 2.0.2</li>
</ul>
</div></div>
```

## Expected Output

yaml file rendered as HTML to look like

```yaml
---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.5
before_install: gem install bundler -v 2.0.2

```

## Environment details:

* OS: Arch Linux
* Ruby version (`ruby -v`): `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]`
* YARD version (`yard -v`): `yard 0.9.22`
* Relevant software dependency/versions:
  * `redcarpet (3.5.0)`
